export const AllRecommended = [
    {
        "Name": "Chicken Roast",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A couple of simple ingredients with no-fuss prep make a roast chicken that many swear is the juiciest they've ever eaten.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/ywzqqskasfb7aszqaoud",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Mutton Roast",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Carefully, add the onion slices, salt and mutton slices to the pan. Deep fry the onion and mutton slices till they get golden brown in colour.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/hpirtpy349a0zu7miw3p",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Egg Bhurji",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A delightful North Indian starter featuring fluffy scrambled eggs cooked to perfection.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,c_fit/vrtjvnuys4ryh9wg14hz",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Paneer Masala",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A rich and flavorful North Indian main course featuring succulent pieces of paneer in a tantalizing gravy.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,c_fit/hgxakh0n08dsl56jfbz0",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Butter Paneer",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Paneer butter masala, also known as butter paneer is a rich & creamy curry made with paneer, spices, onions, tomatoes, cashews and butter.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/eudjfp4ys0imirildxks",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Kadai",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Kadai chicken is a delicious, spicy & flavorful dish made with chicken, onions, tomatoes, ginger, garlic & fresh ground spices known as kadai masala.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/sc8gpriuabvx7fmeiuf9",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Korma",
        "Price": 250,
        "Rating": 3.4,
        "Text": "North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts- looks spectacular.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/qb41u5gjb19ikjnanlec",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Masala",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Chicken Masala Curry is an Indian chicken curry where chicken pieces are marinated and then cooked in a delicious onion-tomato-based gravy.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/sisvvn0dfmoocbxyreev",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Mughlai",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Mughlai Chicken is a restaurant style, north Indian recipe with a creamy, dark brown onion gravy that will have you licking the plate!",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/fh2dxv9fh4ply41m9tom",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Butter Chicken",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Butter chicken is a popular Indian dish made with chicken, spices, tomatoes & cream.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/oghuawtlzw4rz1rtx1pc",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Dal Fry",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A comforting and delicious preparation made with mixed daal cooked and tempered with onions, chillies and more in pure ghee.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/oehwlah6t2glfzn9oxfb",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Dal Tadka",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Dal tadka is a popular Indian dish where cooked spiced lentils are finished with a tempering made of ghee/ oil and spices.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/ofyj001cxsk5e86ii5zg",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Egg Curry",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A flavorful and savory North Indian delight featuring egg.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/dwfvpco2zpddfsys3h9a",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Egg Masala",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A flavorful North Indian delicacy featuring eggs simmered in a rich masala gravy.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/ngljrc0nudaiae3ermn6",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Mutton Korma",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Mutton korma is a delicious dish where mutton is slow cooked with yogurt, spices and ghee until all of the flavors are infused.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/frras7x315wqpoextt38",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Mutton Curry",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A flavorsome and aromatic main course dish from North India highlighting succulent mutton cooked in a rich and savory gravy.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/eln284xsrql0sviyey0u",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Keema Kaleji",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A delightful North Indian main course dish showcasing tender meat paired with flavorful, aromatic spices.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/pbbyskcjdcydfjil8gkr",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Jeera Rice",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A fragrant and flavorful rice dish that is sure to delight your taste buds.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/ayc2loluppm6oikoz2wj",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Biryani",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Richly flavored aromatic rice layered with marinated chicken pieces in a delicate blend of whole spices.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/lln3zxpll8pshaeqrgr9",
        "link": "/Help",
        "quantity": 1,
    }
];

export const AllStarters = [
    {
        "Name": "Dal Chawal",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Lentil or a combination of lentils are pressure-cooked (with or without spices) and is served over cooked rice.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/29/ebaec9e4-ec93-4d8d-bf45-348e07055e1e_66590361-464b-4d62-9167-89a8f4dab4ad.JPG",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Roast",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A couple of simple ingredients with no-fuss prep make a roast chicken that many swear is the juiciest they've ever eaten.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/ywzqqskasfb7aszqaoud",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Mutton Roast",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Carefully, add the onion slices, salt and mutton slices to the pan. Deep fry the onion and mutton slices till they get golden brown in colour.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/hpirtpy349a0zu7miw3p",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Chilli",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Chilli Chicken is a sweet, spicy and crispy appetizer, most popular in Indo-Chinese cuisine. Crispy marinated chicken is sauteed in a spicy",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/29/10fcc21e-ce86-48e9-88ab-1d76d5e77fdb_cb99eeb7-1520-4f28-9ff0-c39e79644b98.JPG",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Keema",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Savory and succulent, this North Indian starter promises a burst of flavors that will leave you craving for more.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/28/67311e44-3b38-4804-855a-d9bd00b201b9_17eea42b-eb8d-4cd7-b2c5-4b2cc854f331.JPG",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Egg Bhurji ",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A delightful North Indian starter featuring fluffy scrambled eggs cooked to perfection.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/vrtjvnuys4ryh9wg14hz",
        "link": "/Help",
        "quantity": 1,
    },
]


export const AllVeg = [
    {
        "Name": "Paneer Masala",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A rich and flavorful North Indian main course featuring succulent pieces of paneer in a tantalizing gravy.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/hgxakh0n08dsl56jfbz0",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Butter Paneer",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Paneer butter masala, also known as butter paneer is a rich & creamy curry made with paneer, spices, onions, tomatoes, cashews and butter.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/eudjfp4ys0imirildxks",
        "link": "/Help",
        "quantity": 1,
    },
]

export const AllChickenMainCourse = [
    {
        "Name": "Chicken Kadai",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Kadai chicken is a delicious, spicy & flavorful dish made with chicken, onions, tomatoes, ginger, garlic & fresh ground spices known as kadai masala.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/sc8gpriuabvx7fmeiuf9",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Hyderabadi",
        "Price": 250,
        "Rating": 3.4,
        "Text": "",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2025/1/28/0ca71746-a132-4f39-97ee-b1767c2652b7_554f4e7a-d3a5-4265-8aeb-0febabaa54c7.jpg",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Curry",
        "Price": 250,
        "Rating": 3.4,
        "Text": "In this easy Indian chicken curry chicken breasts are slowly simmered in a spicy curry sauce with yogurt, tomatoes, onion, garlic, and ginger.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/b7irx4lfnvyoyztw8b7f",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Korma",
        "Price": 250,
        "Rating": 3.4,
        "Text": "North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts- looks spectacular.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/qb41u5gjb19ikjnanlec",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Masala",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Chicken Masala Curry is an Indian chicken curry where chicken pieces are marinated and then cooked in a delicious onion-tomato-based gravy.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/sisvvn0dfmoocbxyreev",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Bhuna",
        "Price": 250,
        "Rating": 3.4,
        "Text": "This chicken curry gets its name from the cooking technique used to make it. Bhuna means roasting the spices, onion & tomatoes in oil",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/10/1/87ec99fe-1ce6-4dba-a67f-c415fa56bb12_c7e2a0e0-ed8b-4b8c-abcb-e9f308d82367.JPG",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Mughlai",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Mughlai Chicken is a restaurant style, north Indian recipe with a creamy, dark brown onion gravy that will have you licking the plate!",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/fh2dxv9fh4ply41m9tom",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Butter Chicken",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Butter chicken is a popular Indian dish made with chicken, spices, tomatoes & cream.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/oghuawtlzw4rz1rtx1pc",
        "link": "/Help",
        "quantity": 1,
    },
]

export const AllDal = [
    {
        "Name": "Dal Fry",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A comforting and delicious preparation made with mixed daal cooked and tempered with onions, chillies and more in pure ghee.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/oehwlah6t2glfzn9oxfb",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Dal Tadka",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Dal tadka is a popular Indian dish where cooked spiced lentils are finished with a tempering made of ghee/ oil and spices.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/ofyj001cxsk5e86ii5zg",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Dal Special",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A delectable and flavorful North Indian specialty that is sure to satisfy your cravings.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2025/1/20/32815095-6f16-4031-9b2c-2bc81284c161_49f2a4fd-b18a-4225-ae20-1a67bf378b73.JPG",
        "link": "/Help",
        "quantity": 1,
    },
]

export const AllEggMainCourse = [
    {
        "Name": "Egg Curry",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A flavorful and savory North Indian delight featuring egg.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/dwfvpco2zpddfsys3h9a",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Egg Korma",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A flavor-packed North Indian delight featuring tender eggs in a rich and aromatic gravy.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2025/1/23/60033cb5-8c8d-4519-b6b9-61ed9e2fd808_a5005d02-65e9-4710-b92f-7fb760d48a88.JPG",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Egg Masala",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A flavorful North Indian delicacy featuring eggs simmered in a rich masala gravy.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/ngljrc0nudaiae3ermn6",
        "link": "/Help",
        "quantity": 1,
    },
]

export const AllMuttonMainCourse = [
    {
        "Name": "Mutton Korma",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Mutton korma is a delicious dish where mutton is slow cooked with yogurt, spices and ghee until all of the flavors are infused.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/frras7x315wqpoextt38",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Mutton Rogan Juice",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Tender mutton simmered in rich, aromatic gravy, showcasing the flavors of North India.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/4/9/6f44e959-f866-4aa4-af92-129c0a594d5c_2d392aa7-58b0-429d-a332-e4de768a37e2.JPG",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Mutton Curry",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A flavorsome and aromatic main course dish from North India highlighting succulent mutton cooked in a rich and savory gravy.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/eln284xsrql0sviyey0u",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Mutton Mughlai",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Mutton Mughalai is a slow cooked lamb curry made with tomatoes, garlic and garam masala. The dish is rich and perfect for the coldest winter months.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/10/1/02862c25-b5d8-41f3-9b1e-ec6378bbc8a7_67a8da2b-d398-44af-8e99-85e42555355b.JPG",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Keema Kaleji",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A delightful North Indian main course dish showcasing tender meat paired with flavorful, aromatic spices.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/pbbyskcjdcydfjil8gkr",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Mutton Masala",
        "Price": 250,
        "Rating": 3.4,
        "Text": "",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/o005f36vthcjbz2bzfco",
        "link": "/Help",
        "quantity": 1,
    },
]



export const AllMustTry = [
    {
        "Name": "Chicken Kadai+Jeera Rice+5 Tandoori Roti",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Chicken Kadai+Jeera Rice+5 Tandoori Roti",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Chilli+Jeera Rice+6 Tandoori Roti",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Chicken Chilli+Jeera Rice+6 Tandoori Roti",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Mughlai+Jeera Rice+7 Tandoori Roti",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Chicken Mughlai+Jeera Rice+7 Tandoori Roti",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Butter Chicken+Jeera Rice+10 Tandoori Roti",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Butter Chicken+Jeera Rice+10 Tandoori Roti",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Egg Bhurji Curry+Jeera Rice+14 Tandoori Roti",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Egg Bhurji Curry+Jeera Rice+14 Tandoori Roti",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Keema Kaleji+Jeera Rice++5 Tandoori Roti",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Keema Kaleji+Jeera Rice++5 Tandoori Roti",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Keema Kaleji Bhuna+Jeera Rice++5 Tandoori Roti",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Keema Kaleji Bhuna+Jeera Rice++5 Tandoori Roti",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Keema Kaleji+Jeera Rice++5 Tandoori Roti",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Keema Kaleji+Jeera Rice++5 Tandoori Roti",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Keema Kaleji Bhuna+Jeera Rice++5 Tandoori Roti",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Keema Kaleji Bhuna+Jeera Rice++5 Tandoori Roti",
        "link": "/Help",
        "quantity": 1,
    },
]
export const AllRiceAndBiryanis = [
    {
        "Name": "Plain Rice",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A simple yet satisfying vegetarian rice delicacy that exudes natural flavors and delicate aromas.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/29/16f5609b-112d-4fa8-9303-10b1b2317b4d_2fad0baa-73a0-433c-b9e0-50bdd2bfdf31.JPG",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Jeera Rice",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A fragrant and flavorful rice dish that is sure to delight your taste buds.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/ayc2loluppm6oikoz2wj",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Chicken Biryani",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Richly flavored aromatic rice layered with marinated chicken pieces in a delicate blend of whole spices.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/lln3zxpll8pshaeqrgr9",
        "link": "/Help",
        "quantity": 1,
    },
    {
        "Name": "Mutton Biryani",
        "Price": 250,
        "Rating": 3.4,
        "Text": "Deliciously decadent flavored dum rice layered with mutton and indian whole spices cooked in a pot.",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/hcydl6nb4fcanxip5uhf",
        "link": "/Help",
        "quantity": 1,
    },
]
export const AllRoti = [
    {
        "Name": "Tawa Roti",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A charred whole wheat flour Indian bread that is soft and can be served along with any kind of curries",
        "img": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/uawdybpb7flnjpcmbsfh",
        "link": "/Help",
        "quantity": 1,
    },
]
export const AllQuickBites = [
    {
        "Name": "Egg Omelette",
        "Price": 250,
        "Rating": 3.4,
        "Text": "A fluffy and satisfying classic made with eggs, prepared to perfection for a quick and delightful bite.",
        "img": "",
        "link": "/Help",
        "quantity": 1,
    },
]

